/* eslint no-console: 0 */
/* tslint:disable: no-console max-line-length */
import * as fs from 'fs';
import * as path from 'path';
import * as store from '../lib/db/store';
import * as dbobjects from '../lib/db/objects';
import * as dbtypes from '../lib/db/db-types';
import * as credentialsmgr from '../lib/training/credentials';
import * as trainingtypes from '../lib/training/training-types';

const opsArgs = process.argv.slice(2);

if (opsArgs.length !== 2) {
    console.log('usage: node add-tenant-to-pool.js tenantid maxusers');
    process.exit(-1); // eslint-disable-line
}

const tenantid  = opsArgs[0];
const maxusers  = parseInt(opsArgs[1], 10);
const maxprojects = 2;

console.log('tenant           :', tenantid);
console.log('class students   :', maxusers);


function sameProjectTypes(a: dbtypes.ProjectTypeLabel[], b: dbtypes.ProjectTypeLabel[]): boolean
{
    return a.length === b.length && a.slice().sort().join(',') === b.slice().sort().join(',');
}


function sqlStr(value: string | null | undefined): string
{
    if (value === null || value === undefined) {
        return 'NULL';
    }
    return `'${value.replace(/'/g, '\'\'')}'`;
}
function sqlDate(value: Date | null | undefined): string
{
    if (!value) {
        return 'NULL';
    }
    return sqlStr(new Date(value).toISOString());
}
function sqlNum(value: number | null | undefined): string
{
    if (value === null || value === undefined) {
        return 'NULL';
    }
    return String(value);
}


/**
 * Prepares SQL statements that would restore a Bluemix credential set (and the
 *  classifiers trained with it, and the scratch keys that were using it) to
 *  exactly how they were before they get deleted / reset.
 */
function prepareRestoreStatements(
    credentials: trainingtypes.BluemixCredentials,
    classifiers: trainingtypes.ClassifierDbRow[],
    scratchkeys: dbtypes.ScratchKeyDbRow[],
): string[]
{
    const statements: string[] = [];

    const credsrow = dbobjects.getCredentialsAsDbRow(credentials);
    statements.push(
        'INSERT INTO bluemixcredentials ' +
            '(id, classid, servicetype, url, username, password, credstypeid, notes) ' +
        'VALUES ' +
            `(${sqlStr(credsrow.id)}, ${sqlStr(credsrow.classid)}, ${sqlStr(credsrow.servicetype)}, ` +
            `${sqlStr(credsrow.url)}, ${sqlStr(credsrow.username)}, ${sqlStr(credsrow.password)}, ` +
            `${sqlNum(credsrow.credstypeid)}, ${sqlStr(credsrow.notes)});`,
    );

    for (const classifier of classifiers) {
        statements.push(
            'INSERT INTO bluemixclassifiers ' +
                '(id, credentialsid, userid, projectid, classid, servicetype, classifierid, url, name, language, created, expiry) ' +
            'VALUES ' +
                `(${sqlStr(classifier.id)}, ${sqlStr(classifier.credentialsid)}, ${sqlStr(classifier.userid)}, ` +
                `${sqlStr(classifier.projectid)}, ${sqlStr(classifier.classid)}, ${sqlStr(classifier.servicetype)}, ` +
                `${sqlStr(classifier.classifierid)}, ${sqlStr(classifier.url)}, ${sqlStr(classifier.name)}, ` +
                `${sqlStr(classifier.language)}, ${sqlDate(classifier.created)}, ${sqlDate(classifier.expiry)});`,
        );
    }

    for (const scratchkey of scratchkeys) {
        statements.push(
            'UPDATE scratchkeys SET ' +
                `classifierid = ${sqlStr(scratchkey.classifierid)}, ` +
                `serviceurl = ${sqlStr(scratchkey.serviceurl)}, ` +
                `serviceusername = ${sqlStr(scratchkey.serviceusername)}, ` +
                `servicepassword = ${sqlStr(scratchkey.servicepassword)}, ` +
                `updated = ${sqlDate(scratchkey.updated)} ` +
            `WHERE id = ${sqlStr(scratchkey.id)};`,
        );
    }

    return statements;
}


function writeRestoreFile(statements: string[]): string
{
    const logsDir = path.join('.', 'logs');
    if (!fs.existsSync(logsDir)) {
        fs.mkdirSync(logsDir, { recursive : true });
    }

    const filename = `restore-${tenantid.replace(/[^a-zA-Z0-9-]/g, '_')}-${Date.now()}.sql`;
    const filepath = path.join(logsDir, filename);

    const contents =
        `-- restore statements for tenant ${tenantid}\n` +
        `-- generated by add-tenant-to-pool.ts on ${new Date().toISOString()}\n` +
        `-- running this file will undo the removal of this tenant's own text classifier credentials\n\n` +
        statements.join('\n') + '\n';

    fs.writeFileSync(filepath, contents);

    return filepath;
}


async function addTenantToPool(): Promise<dbtypes.ClassTenant>
{
    const exists = await store.checkIfTenantExists(tenantid);

    if (!exists) {
        console.log('creating tenant record...');
        return store.storeManagedClassTenant(tenantid, maxusers, maxprojects, dbtypes.ClassTenantType.ManagedPool);
    }

    console.log('tenant record already exists - checking if it can be safely updated...');

    const existing = await store.getClassTenant(tenantid);
    const expected = dbobjects.getDefaultClassTenant(tenantid);

    const unexpectedDifferences: string[] = [];
    if (existing.tenantType !== expected.tenantType) {
        unexpectedDifferences.push(`tenantType (expected ${expected.tenantType}, found ${existing.tenantType})`);
    }
    if (existing.maxUsers !== expected.maxUsers) {
        unexpectedDifferences.push(`maxUsers (expected ${expected.maxUsers}, found ${existing.maxUsers})`);
    }
    if (existing.maxProjectsPerUser !== expected.maxProjectsPerUser) {
        unexpectedDifferences.push(`maxProjectsPerUser (expected ${expected.maxProjectsPerUser}, found ${existing.maxProjectsPerUser})`);
    }
    if (!sameProjectTypes(existing.supportedProjectTypes, expected.supportedProjectTypes)) {
        unexpectedDifferences.push(`supportedProjectTypes (expected ${expected.supportedProjectTypes}, found ${existing.supportedProjectTypes})`);
    }
    if (existing.textClassifierExpiry === expected.textClassifierExpiry) {
        unexpectedDifferences.push('textClassifierExpiry (expected this to be the only difference from the default, but it matches the default)');
    }

    if (unexpectedDifferences.length > 0) {
        throw new Error('Existing tenant record is not in a recognised state - refusing to modify it automatically. ' +
                        `Unexpected differences from the default tenant: ${unexpectedDifferences.join(', ')}`);
    }

    // an unmanaged tenant's text classifiers are trained using their own Watson API keys
    //  (in the bluemixcredentials table). Moving them into the managed pool means their
    //  students will use the site's own pool of keys (bluemixcredentialspool) instead, so
    //  any of their own keys - and the classifiers trained with them - would be orphaned
    //  if left behind. They need to be cleaned up before the tenant record is updated.
    const ownCredentials = await store.getBluemixCredentialsByClassId(tenantid, 'conv');

    const restoreStatements: string[] = [];

    for (const credentials of ownCredentials) {
        // capture what's about to be removed / reset, so it can be put back if needed
        const classifiers = await store.getClassifiersUsingCredentials(credentials);
        const scratchkeys = await store.getScratchKeysUsingCredentials(credentials);
        restoreStatements.push(...prepareRestoreStatements(credentials, classifiers, scratchkeys));

        console.log('removing unmanaged text classifier credentials', credentials.id, '...');
        await credentialsmgr.deleteBluemixCredentials(credentials);
    }

    if (restoreStatements.length > 0) {
        const restorefile = writeRestoreFile(restoreStatements);
        console.log('restore SQL written to', restorefile);
    }

    console.log('existing tenant record only has a customised text classifier expiry - updating it to add to the pool...');
    return store.updateManagedClassTenant(tenantid, maxusers, maxprojects, dbtypes.ClassTenantType.ManagedPool);
}


console.log('');
console.log('connecting to DB...');
store.init()
    .then(() => {
        return addTenantToPool();
    })
    .then((newtenant) => {
        console.log('done:', newtenant);
    })
    .catch((err) => {
        console.error(err);
    })
    .finally(() => {
        return store.disconnect();
    });
